#!/usr/bin/env ruby

require 'optparse'
require 'swagger/diff'
require 'json/ext'

options = {}
OptionParser.new do |opts|
  opts.banner = 'Usage: swagger-diff [options] <old> <new>'

  opts.on('-c', '--changes',
          'Generate a list of changes between <new>',
          'and <old>') do |c|
    options[:changes] = c
  end

  opts.on('-i', '--incompatibilities',
          'Checks <new> for backwards-compatibility',
          'with <old>. If <new> is incompatible, a',
          'list of incompatibilities will be printed.') do |i|
    options[:incompatibilities] = i
  end
  
  opts.on('-j', '--json',
          'Generate result in JSON format') do |j|
    options[:jsonformat] = j
  end

  opts.on_tail('-h', '--help', 'This message') do
    puts opts
    exit
  end

  opts.on_tail('-v', '--version', 'Display the version') do
    puts Swagger::Diff::VERSION
    exit
  end

  options[:help] = opts
end.parse!

if ARGV.length == 2
  begin
    diff = Swagger::Diff::Diff.new(ARGV[0], ARGV[1])
    if options[:changes]
      if options[:jsonformat]
        puts diff.changes.to_json
      else
        puts diff.changes_message
      end
    else
      unless diff.compatible?
        if options[:jsonformat]
          puts diff.incompatibilities.to_json
        else
          puts diff.incompatibilities_message
        end
      else
        puts "Check backward compatibility OK"
      end
    end
  rescue Exception => e
    puts "Check backward compatibility failed : " + e.message
  end
  
else
  puts options[:help]
end
